/**
 * Freeze the agent Skill's canonical markdown (`src/skill/SKILL.md`) into
 * `src/generated/skillAsset.ts`, the same bake-to-generated-module mechanism the
 * browser assets use (ADR 0007). `scripts/build.ts` runs this before bundling so
 * the baked string is carried inside the single-file binary, which has no source
 * tree, letting `intervu setup` write the Skill out with nothing to read from.
 * Running from source, `SkillAsset.layer` reads `SKILL.md` directly instead, so
 * this only needs re-running before a ship build or to refresh the committed copy.
 */

const generatedPath = `${import.meta.dir}/../src/generated/skillAsset.ts`;
const sourcePath = `${import.meta.dir}/../src/skill/SKILL.md`;

const markdown = await Bun.file(sourcePath).text();
const module = `// @generated by scripts/build-skill.ts - do not edit by hand.
// Regenerate with \`bun run build:skill\`.
export const bakedSkillMarkdown = ${JSON.stringify(markdown)};
`;

await Bun.write(generatedPath, module);
console.error(`built skill asset -> ${generatedPath}`);
