import { buildBrowserAssetsFromSource } from "../src/BrowserAssets.ts";

/**
 * Freeze the browser assets (in-iframe SDK, chrome controller, chrome
 * stylesheet) into `src/generated/browserAssets.ts` (ADR 0007). `scripts/build.ts`
 * runs this first so the baked strings are bundled into the single-file binary,
 * which has no source tree to rebuild from. Running from source, the daemon
 * rebuilds these on start instead, so this only needs re-running before a ship
 * build or to refresh the committed baked copy.
 */

const generatedPath = `${import.meta.dir}/../src/generated/browserAssets.ts`;

const result = await buildBrowserAssetsFromSource();
if (!result.ok) {
  console.error(`build-browser failed: ${result.reason}`);
  process.exit(1);
}

const { sdkJs, chromeJs, chromeCss } = result.bundle;
const module = `// @generated by scripts/build-browser.ts - do not edit by hand.
// Regenerate with \`bun run build:browser\`.
export const bakedSdkJs = ${JSON.stringify(sdkJs)};
export const bakedChromeJs = ${JSON.stringify(chromeJs)};
export const bakedChromeCss = ${JSON.stringify(chromeCss)};
`;

await Bun.write(generatedPath, module);
console.error(`built browser assets -> ${generatedPath}`);
